[env:esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13-1/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit ADS1X15@^2.5.0

build_flags =
    -I src
    -I include
    -I AS8510-library
    -Os
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
      