# Cell Voltage Sensors Configuration
# This file contains all 108 individual cell voltage sensors (u1-u108)
# Include this in your main configuration if you want individual cell monitoring

# Cell Voltage Sensors (u1-u108)
sensor:
  # Cell 1-10
  - platform: template
    name: "u1"
    id: u1
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u2"
    id: u2
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u3"
    id: u3
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u4"
    id: u4
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u5"
    id: u5
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u6"
    id: u6
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u7"
    id: u7
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u8"
    id: u8
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u9"
    id: u9
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u10"
    id: u10
    unit_of_measurement: "V"
    accuracy_decimals: 3

  # Cell 11-20
  - platform: template
    name: "u11"
    id: u11
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u12"
    id: u12
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u13"
    id: u13
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u14"
    id: u14
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u15"
    id: u15
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u16"
    id: u16
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u17"
    id: u17
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u18"
    id: u18
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u19"
    id: u19
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u20"
    id: u20
    unit_of_measurement: "V"
    accuracy_decimals: 3

  # Cell 21-30
  - platform: template
    name: "u21"
    id: u21
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u22"
    id: u22
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u23"
    id: u23
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u24"
    id: u24
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u25"
    id: u25
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u26"
    id: u26
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u27"
    id: u27
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u28"
    id: u28
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u29"
    id: u29
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u30"
    id: u30
    unit_of_measurement: "V"
    accuracy_decimals: 3

  # Cell 31-40
  - platform: template
    name: "u31"
    id: u31
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u32"
    id: u32
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u33"
    id: u33
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u34"
    id: u34
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u35"
    id: u35
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u36"
    id: u36
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u37"
    id: u37
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u38"
    id: u38
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u39"
    id: u39
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u40"
    id: u40
    unit_of_measurement: "V"
    accuracy_decimals: 3

  # Cell 41-50
  - platform: template
    name: "u41"
    id: u41
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u42"
    id: u42
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u43"
    id: u43
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u44"
    id: u44
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u45"
    id: u45
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u46"
    id: u46
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u47"
    id: u47
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u48"
    id: u48
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u49"
    id: u49
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u50"
    id: u50
    unit_of_measurement: "V"
    accuracy_decimals: 3

  # Cell 51-60
  - platform: template
    name: "u51"
    id: u51
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u52"
    id: u52
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u53"
    id: u53
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u54"
    id: u54
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u55"
    id: u55
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u56"
    id: u56
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u57"
    id: u57
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u58"
    id: u58
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u59"
    id: u59
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u60"
    id: u60
    unit_of_measurement: "V"
    accuracy_decimals: 3

  # Cell 61-70
  - platform: template
    name: "u61"
    id: u61
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u62"
    id: u62
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u63"
    id: u63
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u64"
    id: u64
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u65"
    id: u65
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u66"
    id: u66
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u67"
    id: u67
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u68"
    id: u68
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u69"
    id: u69
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u70"
    id: u70
    unit_of_measurement: "V"
    accuracy_decimals: 3

  # Cell 71-80
  - platform: template
    name: "u71"
    id: u71
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u72"
    id: u72
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u73"
    id: u73
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u74"
    id: u74
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u75"
    id: u75
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u76"
    id: u76
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u77"
    id: u77
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u78"
    id: u78
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u79"
    id: u79
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u80"
    id: u80
    unit_of_measurement: "V"
    accuracy_decimals: 3

  # Cell 81-90
  - platform: template
    name: "u81"
    id: u81
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u82"
    id: u82
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u83"
    id: u83
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u84"
    id: u84
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u85"
    id: u85
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u86"
    id: u86
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u87"
    id: u87
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u88"
    id: u88
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u89"
    id: u89
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u90"
    id: u90
    unit_of_measurement: "V"
    accuracy_decimals: 3

  # Cell 91-100
  - platform: template
    name: "u91"
    id: u91
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u92"
    id: u92
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u93"
    id: u93
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u94"
    id: u94
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u95"
    id: u95
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u96"
    id: u96
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u97"
    id: u97
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u98"
    id: u98
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u99"
    id: u99
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u100"
    id: u100
    unit_of_measurement: "V"
    accuracy_decimals: 3

  # Cell 101-108
  - platform: template
    name: "u101"
    id: u101
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u102"
    id: u102
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u103"
    id: u103
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u104"
    id: u104
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u105"
    id: u105
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u106"
    id: u106
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u107"
    id: u107
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "u108"
    id: u108
    unit_of_measurement: "V"
    accuracy_decimals: 3

# Additional lambda code for cell voltage parsing
# Add this to your text_sensor lambda section in the main config:

# Cell voltage parsing (add to the existing lambda in text_sensor):
# else if (param_name == "u1") id(u1).publish_state(value);
# else if (param_name == "u2") id(u2).publish_state(value);
# else if (param_name == "u3") id(u3).publish_state(value);
# ... (continue for all 108 cells)
# else if (param_name == "u108") id(u108).publish_state(value); 