esphome:
  name: teslabmsdisplay
  friendly_name: Tesla BMS Display

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Tesla_BMS_Display_AP"
    password: "12345678"

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable OTA updates
ota:
  platform: esphome
  password: !secret ota_password

# Enable web server
web_server:
  port: 80

# UART for communication with Tesla BMS
uart:
  - id: tesla_bms_uart
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 115200
    data_bits: 8
    parity: NONE
    stop_bits: 1

# Binary sensors for system status
binary_sensor:
  - platform: status
    name: "Tesla BMS Display Status"
    id: display_status

# Sensors for system parameters
sensor:
  # System parameters
  - platform: template
    name: "Number of BMBs"
    id: numbmbs
    unit_of_measurement: "boards"
    accuracy_decimals: 0
    
  - platform: template
    name: "Loop Counter"
    id: loopcnt
    unit_of_measurement: "count"
    accuracy_decimals: 0
    
  - platform: template
    name: "Loop State"
    id: loopstate
    unit_of_measurement: "state"
    accuracy_decimals: 0
    
  - platform: template
    name: "Cells Present"
    id: cellspresent
    unit_of_measurement: "cells"
    accuracy_decimals: 0
    
  - platform: template
    name: "Cells Balancing"
    id: cellsbalancing
    unit_of_measurement: "cells"
    accuracy_decimals: 0

  # Voltage statistics
  - platform: template
    name: "Cell Max Number"
    id: cellmax
    unit_of_measurement: "cell"
    accuracy_decimals: 0
    
  - platform: template
    name: "Cell Min Number"
    id: cellmin
    unit_of_measurement: "cell"
    accuracy_decimals: 0
    
  - platform: template
    name: "Max Voltage"
    id: umax
    unit_of_measurement: "mV"
    accuracy_decimals: 0
    
  - platform: template
    name: "Min Voltage"
    id: umin
    unit_of_measurement: "mV"
    accuracy_decimals: 0
    
  - platform: template
    name: "Voltage Delta"
    id: deltav
    unit_of_measurement: "mV"
    accuracy_decimals: 0

  # Balance control
  - platform: template
    name: "Balance Status"
    id: balance
    unit_of_measurement: "status"
    accuracy_decimals: 0

  # Temperature parameters
  - platform: template
    name: "Chip Temperature"
    id: chipt0
    unit_of_measurement: "°C"
    accuracy_decimals: 1

# Switches for control
switch:
  - platform: template
    name: "Balance Control"
    id: balance_control
    optimistic: true
    restore_state: false

# Buttons for manual control
button:
  - platform: template
    name: "Refresh Parameters"
    id: refresh_params
    on_press:
      - uart.write:
          id: tesla_bms_uart
          data: "param list\n"
      
  - platform: template
    name: "Enable Balance"
    id: enable_balance
    on_press:
      - uart.write:
          id: tesla_bms_uart
          data: "balance on\n"
      
  - platform: template
    name: "Disable Balance"
    id: disable_balance
    on_press:
      - uart.write:
          id: tesla_bms_uart
          data: "balance off\n"

# Interval to periodically request parameters
interval:
  - interval: 5s
    then:
      - uart.write:
          id: tesla_bms_uart
          data: "param list\n" 