dependencies:
  uart: "*"
  sensor: "*"
  switch: "*"

codeowners:
  - "@esphome/core"

requirements:
  esphome: ">=2023.12.0"

external_components:
  - source: github://esphome/esphome
    components: [ uart, sensor, switch ]
    refresh: 0s 